diff -Naur parprouted-0.7/Makefile parprouted-0.7-new/Makefile
--- parprouted-0.7/Makefile	2008-01-27 20:25:38.000000000 -0200
+++ parprouted-0.7-new/Makefile	2008-08-10 10:18:51.000000000 -0300
@@ -6,6 +6,9 @@
 # For ARM:
 # CFLAGS =  -Wall $(EXTRA_CFLAGS)
 LDFLAGS = 
+DESTDIR = 
+prefix = /usr
+mandir = ${prefix}/share/man
 OBJS = parprouted.o arp.o
 
 LIBS = -lpthread
@@ -13,8 +16,8 @@
 all: parprouted
 
 install: all
-	install parprouted /usr/local/sbin
-	install parprouted.8 /usr/local/man/man8
+	install -Dp -m0755 parprouted ${DESTDIR}${prefix}/bin/parprouted
+	install -Dp -m0644 parprouted.8 ${DESTDIR}${mandir}/man8/parprouted.8
 
 clean:
 	rm -f $(OBJS) parprouted core
